const sections = [
  {//completed
    title: "VOTER'S CORNER",
    path: "voters-corner",
    items: [
      { name: "Register in Electoral Roll", link: "https://voters.eci.gov.in/" },
      { name: "Track Your Registration Status", link: "https://voters.eci.gov.in/track-status" },
      { name: "Offline Forms For Registration In E-Roll", link: "/formpage" },
      { name: "Know Your Polling Booth", link: "https://electoralsearch.eci.gov.in/pollingstation" },
      { name: "Know Your BLO, ERO & DEO", link: "https://eci.gov.in/contact/" },
      { name: "List of Booth Level Officers (BLO)", link: "https://docs.google.com/spreadsheets/d/1EoYf_D7jW2FPvVjR7EBavOHkaMbpqElOjjbVSdBcgVQ/edit?gid=112484976#gid=112484976" },
      { name: "SIR Final Electoral Roll w.r.t 01.07.2025", link: "https://voters.eci.gov.in/download-eroll?stateCode=S04" },
      { name: "Search in Electoral Roll", link: "https://electoralsearch.eci.gov.in/" },
      { name: "Form 9, 10, 11, 11A, 11B", link: "https://voters.eci.gov.in/download-statutory-report?stateCode=S04" },
      { name: "List Of Claims & Objections in SSR-2025", link: "https://ceo.bihar.gov.in/ssr/claim_objection.aspx" },
      { name: "Monthly list of Additions, Modifications & Deletions", link: "https://ceo.bihar.gov.in/monthly-pooling/" },
    ],
  },
  {//completed
    title: "VOTER INFORMATION",
    path: "voter-information",
    items: [
      { name: "National Voters Day", link: "/national-voters-day" },
      { name: "Electors Registration (04-Tirhut Graduate Constituency)", link: "https://ceo.bihar.gov.in/tcgconline/" },
      { name: "GC - Tirhut Electoral Roll (Final Roll W.R.T. 01.11.2024)", link: "https://ceo.bihar.gov.in/GCTCPDFVIEW/" },
      { name: "TC/GC Electoral Search", link: "https://ceo.bihar.gov.in/tcgcelectorsearch/" },
      { name: "Claims and Objections (TC & GC)", link: "https://ceo.bihar.gov.in/claim/" },
      { name: "Register Complaints", link: "https://eci-citizenservices.eci.nic.in/default.aspx" },
      { name: "Service Voters and Overseas Voters", link: "https://eci.gov.in/voter/service-overseas-voter/" },
      { name: "PwD Voters", link: "/pwd-voters" },
      { name: "SVEEP (Voter’s Education)", link: "/sveep" },
      { name: "Voter Helpline No: 1950", link: "/voter-helpline" },
      { name: "Fact Check", link: "/fact-check" },
    ],
  },
  {//left
    title: "ELECTIONS",
    path: "elections",
    items: [
      { name: "Important Instructions", link: "/important-instructions" },
      { name: "Status of Ex-Gratia Payments", link: "/ex-gratia-status" },
      { name: "SEMP/DEMP", link: "/semp-demp" },
      { name: "Past Elections", link: "/past-elections" },
      { name: "Electoral Roll", link: "/electoral-roll" },
      { name: "ERMS", link: "/erms" },
      { name: "Election Law", link: "/election-law" },
      { name: "Model Code of Conduct", link: "/model-code-of-conduct" },
      { name: "Judicial References", link: "https://www.eci.gov.in/judicial-reference/" },
    ],
  },
  {//lleft
    title: "MEDIA/PUBLICATION",
    path: "media-publication",
    items: [
      { name: "Workshop/Events", link: "/workshops-events" },
      { name: "Media Corner", link: "/media-corner" },
      { name: "Statistical Report", link: "https://www.eci.gov.in/statistical-reports" },
      { name: "Compendium of Instructions", link: "https://eci.gov.in/files/category/8-compendium-of-instructions/" },
      { name: "Press Release", link: "/press-release" },
      { name: "Handbooks/ Manuals/ Model Check List", link: "https://www.eci.gov.in/error " },
      { name: "Latest News", link: "/latest-news" },
      { name: "Right to Information", link: "/rti" },
      { name: "Tender", link: "/tender" },
    ],
  },
  {//completed
    title: "CANDIDATE/POLITICAL PARTIES",
    path: "candidate-parties",
    items: [
      { name: "Political Parties", link: "/political-party-registration" },
      { name: "Candidate Affidavits", link: "/candidate-affidavits" },
      { name: "Candidate Nominations/ Other forms", link: "/formpage" },
      { name: "Election Symbols", link: "/party-symbols" },
      { name: "Candidate/Political Parties Expenditure Balance Sheets", link: "/expenditure-balance-sheets" },
      { name: "List of Disqualified Persons", link: "https://ceoelection.bihar.gov.in/pdf/List_of_Disqualified_Persons.pdf" },
    ],
  },
  {//completed
    title: "EVM/VVPAT",
    path: "evm-vvpat",
    items: [
      { name: "List of EVMs after First & Second Randomisation for General Elections 2024", link: "/evm-randomisation-list" },
      { name: "Credibility of EVM", link: "https://ceoelection.bihar.gov.in/CredibilityOfEVM/EVMPressNote.pdf" },
      { name: "EVM Brochure for Electors", link: "https://ceoelection.bihar.gov.in/pdf/EVM/EVM%20BROCHURE%20FOR%20ELECTORS%202023.pdf" },
      { name: "EVM Brochure for Presiding Officers", link: "https://ceoelection.bihar.gov.in/pdf/EVM/EVM%20Brochure-PO-2023.pdf" },
      { name: "EVM Brochure for Candidates and Political Parties", link: "https://ceoelection.bihar.gov.in/pdf/EVM/EVM%20Brochure%20for%20Candidates%20and%20Political%20Parties%202024.pdf" },
      { name: "FLC OK EVMs for Upcoming Lok Sabha Election 2024", link: "/flc-ok-evms" },
    ],
  },
  {//completed
    title: "CEO OFFICIALS",
    path: "ceo-officials",
    items: [
      { name: "SPARROW", link: "/sparrow" },
      { name: "Budget/Allotments", link: "https://ele.bihar.gov.in/uploadletter/home" },
      { name: "Organizational Structure", link: "/organizational-structure" },
      { name: "DEO’s Portal", link: "https://ele.bihar.gov.in/deo-portal/" },
      { name: "Important Instructions & Letters (CEO Officials)", link: "https://ele.bihar.gov.in/eci-instruction/" },
      { name: "E-Office", link: "https://eoffice.bihar.gov.in/cas/login?service=http%3A%2F%2Feoffice.bihar.gov.in%2Flogin.php" },
      { name: "Asset Declarations", link: "https://bpsm.bihar.gov.in/assets/Home.aspx?P1=1&P2=10&P3=0&P4=0" },
      { name: "Transfers/Postings/Promotions", link: "/transfers-promotions" },
      { name: "Contact Us", link: "/contact-us" },
    ],
  },
  {//left
    title: "REFERENCE MATERIAL",
    path: "reference-material",
    items: [
      { name: "Handbook References", link: "https://ele.bihar.gov.in/handbook-reference/" },
      { name: "Important Maps", link: "/important-maps" },
      { name: "Training Materials", link: "/training-materials" },
      { name: "Hand Books", link: "/hand-books" },
      { name: "e-Books", link: "/ebooks" },
      { name: "Question Bank", link: "/question-bank" },
      { name: "List of AC’s with Division and District", link: "/ac-division-list" },
      { name: "Format 1-8 (Final Roll)", link: "/format-1-8" },
      { name: "Form-20 | Form-21E", link: "/form-20-21e" },
      { name: "Polling Station List", link: "/polling-station-list" },
    ],
  },
];


export default sections;