import React from "react";
import Nav from "../Components/Nav";
import { Link } from "react-router-dom";

const Sir_finalroll_forfullAC = () => {
  // AC data list — you can easily expand this later
  const acList = [
    { "acNo": 1, "acName": "VALMIKINAGAR", "downloadLink": "#" },
    { "acNo": 2, "acName": "RAMNAGAR", "downloadLink": "#" },
    { "acNo": 3, "acName": "NARKATIAGANJ", "downloadLink": "#" },
    { "acNo": 4, "acName": "BAGAHA", "downloadLink": "#" },
    { "acNo": 5, "acName": "LAURIYA", "downloadLink": "#" },
    { "acNo": 6, "acName": "NAUTAN", "downloadLink": "#" },
    { "acNo": 7, "acName": "CHANPATIA", "downloadLink": "#" },
    { "acNo": 8, "acName": "BETTIAH", "downloadLink": "#" },
    { "acNo": 9, "acName": "SIKTA", "downloadLink": "#" },
    { "acNo": 10, "acName": "RAXAUL", "downloadLink": "#" },
    { "acNo": 11, "acName": "SUGAULI", "downloadLink": "#" },
    { "acNo": 12, "acName": "NARKATIA", "downloadLink": "#" },
    { "acNo": 13, "acName": "HARSIDHI", "downloadLink": "#" },
    { "acNo": 14, "acName": "GOVINDGANJ", "downloadLink": "#" },
    { "acNo": 15, "acName": "KESARIA", "downloadLink": "#" },
    { "acNo": 16, "acName": "KALYANPUR", "downloadLink": "#" },
    { "acNo": 17, "acName": "PIPRA", "downloadLink": "#" },
    { "acNo": 18, "acName": "MADHUBAN", "downloadLink": "#" },
    { "acNo": 19, "acName": "MOTIHARI", "downloadLink": "#" },
    { "acNo": 20, "acName": "CHIRAIYA", "downloadLink": "#" },
    { "acNo": 21, "acName": "DHAKA", "downloadLink": "#" },
    { "acNo": 22, "acName": "SHEOHAR", "downloadLink": "#" },
    { "acNo": 23, "acName": "RIGA", "downloadLink": "#" },
    { "acNo": 24, "acName": "BATHNAHA", "downloadLink": "#" },
    { "acNo": 25, "acName": "PARIHAR", "downloadLink": "#" },
    { "acNo": 26, "acName": "SURSAND", "downloadLink": "#" },
    { "acNo": 27, "acName": "BAJPATTI", "downloadLink": "#" },
    { "acNo": 28, "acName": "SITAMARHI", "downloadLink": "#" },
    { "acNo": 29, "acName": "RUNNISAIDPUR", "downloadLink": "#" },
    { "acNo": 30, "acName": "BELSAND", "downloadLink": "#" },
    { "acNo": 31, "acName": "HARLAKHI", "downloadLink": "#" },
    { "acNo": 32, "acName": "BENIPATTI", "downloadLink": "#" },
    { "acNo": 33, "acName": "KHAJAULI", "downloadLink": "#" },
    { "acNo": 34, "acName": "BABUBARHI", "downloadLink": "#" },
    { "acNo": 35, "acName": "BISFI", "downloadLink": "#" },
    { "acNo": 36, "acName": "MADHUBANI", "downloadLink": "#" },
    { "acNo": 37, "acName": "RAJNAGAR", "downloadLink": "#" },
    { "acNo": 38, "acName": "JHANJHARPUR", "downloadLink": "#" },
    { "acNo": 39, "acName": "PHULPARAS", "downloadLink": "#" },
    { "acNo": 40, "acName": "LAUKAHA", "downloadLink": "#" },
    { "acNo": 41, "acName": "NIRMALI", "downloadLink": "#" },
    { "acNo": 42, "acName": "PIPRA", "downloadLink": "#" },
    { "acNo": 43, "acName": "SUPAUL", "downloadLink": "#" },
    { "acNo": 44, "acName": "TRIVENIGANJ", "downloadLink": "#" },
    { "acNo": 45, "acName": "CHHATAPUR", "downloadLink": "#" },
    { "acNo": 46, "acName": "NARPATGANJ", "downloadLink": "#" },
    { "acNo": 47, "acName": "RANIGANJ", "downloadLink": "#" },
    { "acNo": 48, "acName": "FORBESGANJ", "downloadLink": "#" },
    { "acNo": 49, "acName": "ARARIA", "downloadLink": "#" },
    { "acNo": 50, "acName": "JOKIHAT", "downloadLink": "#" },
    { "acNo": 51, "acName": "SIKTI", "downloadLink": "#" },
    { "acNo": 52, "acName": "BAHADURGANJ", "downloadLink": "#" },
    { "acNo": 53, "acName": "THAKURGANJ", "downloadLink": "#" },
    { "acNo": 54, "acName": "KISHANGANJ", "downloadLink": "#" },
    { "acNo": 55, "acName": "KOCHADHAMAN", "downloadLink": "#" },
    { "acNo": 56, "acName": "AMOUR", "downloadLink": "#" },
    { "acNo": 57, "acName": "BAISI", "downloadLink": "#" },
    { "acNo": 58, "acName": "KASBA", "downloadLink": "#" },
    { "acNo": 59, "acName": "BANMANKHI", "downloadLink": "#" },
    { "acNo": 60, "acName": "RUPAULI", "downloadLink": "#" },
    { "acNo": 61, "acName": "DHAMDAHA", "downloadLink": "#" },
    { "acNo": 62, "acName": "PURNIA", "downloadLink": "#" },
    { "acNo": 63, "acName": "KATIHAR", "downloadLink": "#" },
    { "acNo": 64, "acName": "KADWA", "downloadLink": "#" },
    { "acNo": 65, "acName": "BALRAMPUR", "downloadLink": "#" },
    { "acNo": 66, "acName": "PRANPUR", "downloadLink": "#" },
    { "acNo": 67, "acName": "MANIHARI", "downloadLink": "#" },
    { "acNo": 68, "acName": "BARARI", "downloadLink": "#" },
    { "acNo": 69, "acName": "KORHA", "downloadLink": "#" },
    { "acNo": 70, "acName": "ALAMNAGAR", "downloadLink": "#" },
    { "acNo": 71, "acName": "BIHARIGANJ", "downloadLink": "#" },
    { "acNo": 72, "acName": "SINGHESHWAR", "downloadLink": "#" },
    { "acNo": 73, "acName": "MADHEPURA", "downloadLink": "#" },
    { "acNo": 74, "acName": "SONBARSHA", "downloadLink": "#" },
    { "acNo": 75, "acName": "SAHARSA", "downloadLink": "#" },
    { "acNo": 76, "acName": "SIMRI BAKHTIARPUR", "downloadLink": "#" },
    { "acNo": 77, "acName": "MAHISHI", "downloadLink": "#" },
    { "acNo": 78, "acName": "KUSHESHWAR ASTHAN", "downloadLink": "#" },
    { "acNo": 79, "acName": "GAURA BAURAM", "downloadLink": "#" },
    { "acNo": 80, "acName": "BENIPUR", "downloadLink": "#" },
    { "acNo": 81, "acName": "ALINAGAR", "downloadLink": "#" },
    { "acNo": 82, "acName": "DARBHANGA RURAL", "downloadLink": "#" },
    { "acNo": 83, "acName": "DARBHANGA", "downloadLink": "#" },
    { "acNo": 84, "acName": "HAYAGHAT", "downloadLink": "#" },
    { "acNo": 85, "acName": "BAHADURPUR", "downloadLink": "#" },
    { "acNo": 86, "acName": "KEOTI", "downloadLink": "#" },
    { "acNo": 87, "acName": "JALE", "downloadLink": "#" },
    { "acNo": 88, "acName": "GAIGHAT", "downloadLink": "#" },
    { "acNo": 89, "acName": "AURAI", "downloadLink": "#" },
    { "acNo": 90, "acName": "MINAPUR", "downloadLink": "#" },
    { "acNo": 91, "acName": "BOCHAHA", "downloadLink": "#" },
    { "acNo": 92, "acName": "SAKRA", "downloadLink": "#" },
    { "acNo": 93, "acName": "KURHANI", "downloadLink": "#" },
    { "acNo": 94, "acName": "MUZAFFARPUR", "downloadLink": "#" },
    { "acNo": 95, "acName": "KANTI", "downloadLink": "#" },
    { "acNo": 96, "acName": "BARURAJ", "downloadLink": "#" },
    { "acNo": 97, "acName": "PAROO", "downloadLink": "#" },
    { "acNo": 98, "acName": "SAHEBGANJ", "downloadLink": "#" },
    { "acNo": 99, "acName": "BAIKUNTHPUR", "downloadLink": "#" },
    { "acNo": 100, "acName": "BARAULI", "downloadLink": "#" },
    { "acNo": 101, "acName": "GOPALGANJ", "downloadLink": "#" },
    { "acNo": 102, "acName": "KUCHAIKOTE", "downloadLink": "#" },
    { "acNo": 103, "acName": "BHOREY", "downloadLink": "#" },
    { "acNo": 104, "acName": "HATHUA", "downloadLink": "#" },
    { "acNo": 105, "acName": "SIWAN", "downloadLink": "#" },
    { "acNo": 106, "acName": "ZIRADEI", "downloadLink": "#" },
    { "acNo": 107, "acName": "DARAULI", "downloadLink": "#" },
    { "acNo": 108, "acName": "RAGHUNATHPUR", "downloadLink": "#" },
    { "acNo": 109, "acName": "DARAUNDHA", "downloadLink": "#" },
    { "acNo": 110, "acName": "BARHARIA", "downloadLink": "#" },
    { "acNo": 111, "acName": "GORIAKOTHI", "downloadLink": "#" },
    { "acNo": 112, "acName": "MAHARAJGANJ", "downloadLink": "#" },
    { "acNo": 113, "acName": "EKMA", "downloadLink": "#" },
    { "acNo": 114, "acName": "MANJHI", "downloadLink": "#" },
    { "acNo": 115, "acName": "BANIAPUR", "downloadLink": "#" },
    { "acNo": 116, "acName": "TARAIYA", "downloadLink": "#" },
    { "acNo": 117, "acName": "MARHAURA", "downloadLink": "#" },
    { "acNo": 118, "acName": "CHAPRA", "downloadLink": "#" },
    { "acNo": 119, "acName": "GARKHA", "downloadLink": "#" },
    { "acNo": 120, "acName": "AMNOUR", "downloadLink": "#" },
    { "acNo": 121, "acName": "PARSA", "downloadLink": "#" },
    { "acNo": 122, "acName": "SONEPUR", "downloadLink": "#" },
    { "acNo": 123, "acName": "HAJIPUR", "downloadLink": "#" },
    { "acNo": 124, "acName": "LALGANJ", "downloadLink": "#" },
    { "acNo": 125, "acName": "VAISHALI", "downloadLink": "#" },
    { "acNo": 126, "acName": "MAHUA", "downloadLink": "#" },
    { "acNo": 127, "acName": "RAJAPAKAR", "downloadLink": "#" },
    { "acNo": 128, "acName": "RAGHOPUR", "downloadLink": "#" },
    { "acNo": 129, "acName": "MAHNAR", "downloadLink": "#" },
    { "acNo": 130, "acName": "PATEPUR", "downloadLink": "#" },
    { "acNo": 131, "acName": "KALYANPUR", "downloadLink": "#" },
    { "acNo": 132, "acName": "WARISNAGAR", "downloadLink": "#" },
    { "acNo": 133, "acName": "SAMASTIPUR", "downloadLink": "#" },
    { "acNo": 134, "acName": "UJIARPUR", "downloadLink": "#" },
    { "acNo": 135, "acName": "MORWA", "downloadLink": "#" },
    { "acNo": 136, "acName": "SARAIRANJAN", "downloadLink": "#" },
    { "acNo": 137, "acName": "MOHIUDDINNAGAR", "downloadLink": "#" },
    { "acNo": 138, "acName": "BIBHUTIPUR", "downloadLink": "#" },
    { "acNo": 139, "acName": "ROSERA", "downloadLink": "#" },
    { "acNo": 140, "acName": "HASANPUR", "downloadLink": "#" },
    { "acNo": 141, "acName": "CHERIA BARIARPUR", "downloadLink": "#" },
    { "acNo": 142, "acName": "BACHHWARA", "downloadLink": "#" },
    { "acNo": 143, "acName": "TEGHRA", "downloadLink": "#" },
    { "acNo": 144, "acName": "MATIHANI", "downloadLink": "#" },
    { "acNo": 145, "acName": "SAHEBPUR KAMAL", "downloadLink": "#" },
    { "acNo": 146, "acName": "BEGUSARAI", "downloadLink": "#" },
    { "acNo": 147, "acName": "BAKHRI", "downloadLink": "#" },
    { "acNo": 148, "acName": "ALAULI", "downloadLink": "#" },
    { "acNo": 149, "acName": "KHAGARIA", "downloadLink": "#" },
    { "acNo": 150, "acName": "BELDAUR", "downloadLink": "#" },
    { "acNo": 151, "acName": "PARBATTA", "downloadLink": "#" },
    { "acNo": 152, "acName": "BIHPUR", "downloadLink": "#" },
    { "acNo": 153, "acName": "GOPALPUR", "downloadLink": "#" },
    { "acNo": 154, "acName": "PIRPAINTI", "downloadLink": "#" },
    { "acNo": 155, "acName": "KAHALGAON", "downloadLink": "#" },
    { "acNo": 156, "acName": "BHAGALPUR", "downloadLink": "#" },
    { "acNo": 157, "acName": "SULTANGANJ", "downloadLink": "#" },
    { "acNo": 158, "acName": "NATHNAGAR", "downloadLink": "#" },
    { "acNo": 159, "acName": "AMARPUR", "downloadLink": "#" },
    { "acNo": 160, "acName": "DHAURAIYA", "downloadLink": "#" },
    { "acNo": 161, "acName": "BANKA", "downloadLink": "#" },
    { "acNo": 162, "acName": "KATORIA", "downloadLink": "#" },
    { "acNo": 163, "acName": "BELHAR", "downloadLink": "#" },
    { "acNo": 164, "acName": "TARAPUR", "downloadLink": "#" },
    { "acNo": 165, "acName": "MUNGER", "downloadLink": "#" },
    { "acNo": 166, "acName": "JAMALPUR", "downloadLink": "#" },
    { "acNo": 167, "acName": "SURAJGARHA", "downloadLink": "#" },
    { "acNo": 168, "acName": "LAKHISARAI", "downloadLink": "#" },
    { "acNo": 169, "acName": "SHEIKHPURA", "downloadLink": "#" },
    { "acNo": 170, "acName": "BARBIGHA", "downloadLink": "#" },
    { "acNo": 171, "acName": "ASTHAWAN", "downloadLink": "#" },
    { "acNo": 172, "acName": "BIHARSHARIF", "downloadLink": "#" },
    { "acNo": 173, "acName": "RAJGIR", "downloadLink": "#" },
    { "acNo": 174, "acName": "ISLAMPUR", "downloadLink": "#" },
    { "acNo": 175, "acName": "HILSA", "downloadLink": "#" },
    { "acNo": 176, "acName": "NALANDA", "downloadLink": "#" },
    { "acNo": 177, "acName": "HARNAUT", "downloadLink": "#" },
    { "acNo": 178, "acName": "MOKAMA", "downloadLink": "#" },
    { "acNo": 179, "acName": "BARH", "downloadLink": "#" },
    { "acNo": 180, "acName": "BAKHTIARPUR", "downloadLink": "#" },
    { "acNo": 181, "acName": "DIGHA", "downloadLink": "#" },
    { "acNo": 182, "acName": "BANKIPUR", "downloadLink": "#" },
    { "acNo": 183, "acName": "KUMHRAR", "downloadLink": "#" },
    { "acNo": 184, "acName": "PATNA SAHIB", "downloadLink": "#" },
    { "acNo": 185, "acName": "FATUHA", "downloadLink": "#" },
    { "acNo": 186, "acName": "DANAPUR", "downloadLink": "#" },
    { "acNo": 187, "acName": "MANER", "downloadLink": "#" },
    { "acNo": 188, "acName": "PHULWARI", "downloadLink": "#" },
    { "acNo": 189, "acName": "MASAURHI", "downloadLink": "#" },
    { "acNo": 190, "acName": "PALIGANJ", "downloadLink": "#" },
    { "acNo": 191, "acName": "BIKRAM", "downloadLink": "#" },
    { "acNo": 192, "acName": "SANDESH", "downloadLink": "#" },
    { "acNo": 193, "acName": "BARHARA", "downloadLink": "#" },
    { "acNo": 194, "acName": "ARRAH", "downloadLink": "#" },
    { "acNo": 195, "acName": "AGIAON", "downloadLink": "#" },
    { "acNo": 196, "acName": "TARARI", "downloadLink": "#" },
    { "acNo": 197, "acName": "JAGDISHPUR", "downloadLink": "#" },
    { "acNo": 198, "acName": "SHAHPUR", "downloadLink": "#" },
    { "acNo": 199, "acName": "BRAHAMPUR", "downloadLink": "#" },
    { "acNo": 200, "acName": "BUXAR", "downloadLink": "#" },
    { "acNo": 201, "acName": "DUMRAON", "downloadLink": "#" },
    { "acNo": 202, "acName": "RAJPUR", "downloadLink": "#" },
    { "acNo": 203, "acName": "RAMGARH", "downloadLink": "#" },
    { "acNo": 204, "acName": "MOHANIA", "downloadLink": "#" },
    { "acNo": 205, "acName": "BHABUA", "downloadLink": "#" },
    { "acNo": 206, "acName": "CHAINPUR", "downloadLink": "#" },
    { "acNo": 207, "acName": "CHENARI", "downloadLink": "#" },
    { "acNo": 208, "acName": "SASARAM", "downloadLink": "#" },
    { "acNo": 209, "acName": "KARGAHAR", "downloadLink": "#" },
    { "acNo": 210, "acName": "DINARA", "downloadLink": "#" },
    { "acNo": 211, "acName": "NOKHA", "downloadLink": "#" },
    { "acNo": 212, "acName": "DEHRI", "downloadLink": "#" },
    { "acNo": 213, "acName": "KARAKAT", "downloadLink": "#" },
    { "acNo": 214, "acName": "ARWAL", "downloadLink": "#" },
    { "acNo": 215, "acName": "KURTHA", "downloadLink": "#" },
    { "acNo": 216, "acName": "JEHANABAD", "downloadLink": "#" },
    { "acNo": 217, "acName": "GHOSI", "downloadLink": "#" },
    { "acNo": 218, "acName": "MAKHDUMPUR", "downloadLink": "#" },
    { "acNo": 219, "acName": "GOH", "downloadLink": "#" },
    { "acNo": 220, "acName": "OBRA", "downloadLink": "#" },
    { "acNo": 221, "acName": "NABINAGAR", "downloadLink": "#" },
    { "acNo": 222, "acName": "KUTUMBA", "downloadLink": "#" },
    { "acNo": 223, "acName": "AURANGABAD", "downloadLink": "#" },
    { "acNo": 224, "acName": "RAFIGANJ", "downloadLink": "#" },
    { "acNo": 225, "acName": "GURUA", "downloadLink": "#" },
    { "acNo": 226, "acName": "SHERGHATI", "downloadLink": "#" },
    { "acNo": 227, "acName": "IMAMGANJ", "downloadLink": "#" },
    { "acNo": 228, "acName": "BARACHATTI", "downloadLink": "#" },
    { "acNo": 229, "acName": "BODH GAYA", "downloadLink": "#" },
    { "acNo": 230, "acName": "GAYA TOWN", "downloadLink": "#" },
    { "acNo": 231, "acName": "TIKARI", "downloadLink": "#" },
    { "acNo": 232, "acName": "BELAGANJ", "downloadLink": "#" },
    { "acNo": 233, "acName": "ATRI", "downloadLink": "#" },
    { "acNo": 234, "acName": "WAZIRGANJ", "downloadLink": "#" },
    { "acNo": 235, "acName": "RAJAULI", "downloadLink": "#" },
    { "acNo": 236, "acName": "HISUA", "downloadLink": "#" },
    { "acNo": 237, "acName": "NAWADA", "downloadLink": "#" },
    { "acNo": 238, "acName": "GOBINDPUR", "downloadLink": "#" },
    { "acNo": 239, "acName": "WARSALIGANJ", "downloadLink": "#" },
    { "acNo": 240, "acName": "SIKANDRA", "downloadLink": "#" },
    { "acNo": 241, "acName": "JAMUI", "downloadLink": "#" },
    { "acNo": 242, "acName": "JHAJHA", "downloadLink": "#" },
    { "acNo": 243, "acName": "CHAKAI", "downloadLink": "#" }
]

  return (
    <>

      <div className="mt-10 bg-blue-200 rounded-xl shadow-lg p-8 max-w-3xl mx-auto border border-gray-200">
        <h2 className="text-2xl font-semibold mb-6 text-center text-blue-950">
          Bihar SIR Final Roll 2025
        </h2>

        {/* Table Section */}
        <div className="table">
          {/* Table Header */}
          <div className="head flex justify-between text-white px-4 py-2 rounded font-bold bg-blue-950">
            <span>AC No.</span>
            <span>AC Name</span>
            <span>Action</span>
          </div>

          {/* Dynamic Rows */}
          {acList.map((ac) => (
            <div
              key={ac.acNo}
              className="data flex justify-between items-center my-2 px-4 py-2 rounded font-semibold bg-white text-gray-800 hover:bg-blue-50 transition"
            >
              <span>{ac.acNo}</span>
              <span className="capitalize">{ac.acName}</span>
              <Link
                to={ac.downloadLink}
                className="bg-blue-600 text-white px-3 py-1 rounded hover:bg-blue-700 text-sm font-medium"
              >
                Download
              </Link>
            </div>
          ))}
        </div>
      </div>
    </>
  );
};

export default Sir_finalroll_forfullAC;
